Новая папка (2)/lab6/config/routes.rb
Rails.application.routes.draw do
  root 'labs#index'
  resources :labs do
    resources :marks
  end
end

Новая папка (2)/lab6/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Новая папка (2)/lab6/app/models/lab.rb
class Lab < ApplicationRecord
  has_one :mark, dependent: :delete
  validates :title, presence: true,
                    length: { maximum: 250 }
  validates :text, length: {maximum: 500}
end

Новая папка (2)/lab6/app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :lab
  validates :points, numericality: { only_integer: true }, :inclusion => 1..100, presence: true
end

Новая папка (2)/lab6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Новая папка (2)/lab6/app/controllers/labs_controller.rb
class LabsController < ApplicationController
  def index
    @labs = Lab.all
  end

  def new
    @lab = Lab.new
  end

  def create
    @lab = Lab.new(lab_params)

    if @lab.save
      redirect_to labs_path
    else
      render "new"
    end
  end

  def destroy
    Lab.destroy(params[:id])
    redirect_to labs_path
  end

  private def lab_params
    params.require(:lab).permit(:title, :text)
  end
end

Новая папка (2)/lab6/app/controllers/marks_controller.rb
class MarksController < ApplicationController

  LETTER = {
    1..34 => "F",
    35..59 => "FX",
    60..66 => "E",
    67..74 => "D",
    75..81 => "C",
    82..89 => "B",
    90..100 => "A",
  }
  def new
    @mark = Mark.new
  end

  def create
    points = mark_params[:points].to_i
    @mark = Mark.create(points: points, letter: LETTER.select {|f| f === points }.values.first)

    if points > 0 && points <= 100
    @lab = Lab.find(params[:lab_id])
    @lab.mark = @mark
    end

    if @mark.valid?
      redirect_to "/"
    else
      render "new"
    end
  end

  private def mark_params
    params.require(:mark).permit(:points)
  end
end

Новая папка (2)/lab6/app/helpers/application_helper.rb
module ApplicationHelper
end

Новая папка (2)/lab6/app/helpers/labs_helper.rb
module LabsHelper
end

Новая папка (2)/lab6/app/helpers/marks_helper.rb
module MarksHelper
end

Новая папка (2)/lab6/app/views/labs/index.html.erb
<div class="lab">
  <h1 class="lab__logo">Labs reports</h1>
  <div class="lab__container">
    <%= link_to new_lab_path do %>
      <button class="btn">Add report</button>
    <% end %>
    <% @labs.each do |lab| %>
      <div class="report">
        <div class="report__title"><%= lab.title %></div>
        <div class="report__text"><%= lab.text %></div>
        <div class="report__btns">

          <% if !lab.mark %>
            <%= link_to new_lab_mark_url lab do %>
              <button class="btn">Add mark</button>
            <% end %>
          <% end %>

          <% if lab.mark %>
            <span class="report__mark">Mark: <%= lab.mark.letter %> (<%= lab.mark.points %>)</span>
          <% end %>

          <%= link_to lab, method: :delete do %>
            <button class="btn">Remove</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

Новая папка (2)/lab6/app/views/labs/new.html.erb
<div class="form-new-report">
  <div class="form-new-report__container">
    <%= form_for :lab, url: labs_path do |f| %>
      <div class="form-new-report__name"><%= f.label :title %></div>
      <%= f.text_field :title, class: "form-new-report__title-input", placeholder: "Title" %>

      <div class="form-new-report__name"><%= f.label :text %></div>
      <%= f.text_area :text, class: "form-new-report__text-input", placeholder: "Text" %>

      <div class="form-new-report__submit">
        <% if @lab.errors.any? %>
          <% @lab.errors.full_messages.each do |msg| %>
            <div class="form-new-report__valid-message"><%= msg %></div>
          <% end %>
        <% end %>
        <%= f.submit class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

Новая папка (2)/lab6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Новая папка (2)/lab6/app/views/marks/new.html.erb
<div class="form-new-mark">
  <div class="form-new-mark__container">
    <%= form_for :mark, url: lab_marks_path do |f| %>
      <div class="form-new-mark__name">
        <%= f.label :points %>
      </div>
        <%= f.text_field :points, class: "form-new-mark__mark-input", type: "number"%>
      <div class="form-new-mark__submit">
        <% if @mark.errors.any? %>
          <div class="form-new-mark__valid-message">
            Enter an points from 1-100
          </div>
        <% end %>
        <%= f.submit class: "btn" %>
      </div>
    <% end %>
  </div>
</div>